# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .ui.res import res

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1872, 1291)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(290, 90, 1481, 831))
        self.frame.setMinimumSize(QtCore.QSize(1481, 831))
        self.frame.setStyleSheet("#frame{\n"
                                 "\n"
                                 "    background-color: rgb(248, 249, 250);\n"
                                 "    border: 1px solid rgb(200, 200, 200);\n"
                                 "    border-radius: 8px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(248, 249, 250);\n"
                                   "border-top-left-radius:8px;\n"
                                   "border-top-right-radius:8px;\n"
                                   "border-bottom: 1px solid rgb(220, 220, 220);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:none;\n"
                                      "font: 20pt \"微软雅黑\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/地球.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2.addWidget(self.frame_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_relogin = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_relogin.setFont(font)
        self.pushButton_relogin.setStyleSheet("QPushButton{\n"
                                              "background-color: rgb(255, 255, 255);\n"
                                              "    border: 2px solid rgb(51, 51, 51);\n"
                                              "    color: rgb(51, 51, 51);\n"
                                              "    font: 40pt \"微软雅黑\";\n"
                                              "    border-radius: 8px;\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "    background-color: rgb(230, 240, 255);\n"
                                              "    border: 2px solid rgb(34, 34, 34);\n"
                                              "    color: rgb(34, 34, 34);\n"
                                              "}\n"
                                              "QPushButton:pressed{\n"
                                              "    background-color: rgb(210, 225, 255);\n"
                                              "    padding-left:3px;\n"
                                              "    padding-top:3px;\n"
                                              "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_relogin.setIcon(icon1)
        self.pushButton_relogin.setIconSize(QtCore.QSize(80, 40))
        self.pushButton_relogin.setObjectName("pushButton_relogin")
        self.horizontalLayout_2.addWidget(self.pushButton_relogin)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
                                   "    border:none;\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    padding-bottom:10px\n"
                                   "\n"
                                   "}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minimize (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
                                   "\n"
                                   "    background-color: rgb(240, 242, 245);\n"
                                   "    border-bottom-left-radius:8px;\n"
                                   "    border-top-right-radius:8px;\n"
                                   "    border-right: 1px solid rgb(220, 220, 220);\n"
                                   "}\n"
                                   "#frame_6 QPushButton{\n"
                                   "    background-color: rgb(255, 255, 255);\n"
                                   "    border: 2px solid rgb(51, 51, 51);\n"
                                   "    color: rgb(51, 51, 51);\n"
                                   "    font: 50pt \"微软雅黑\";\n"
                                   "    border-radius: 8px;\n"
                                   "    padding: 10px;\n"
                                   "    margin: 5px;\n"
                                   "}\n"
                                   "#frame_6 QPushButton:hover{\n"
                                   "    background-color: rgb(230, 240, 255);\n"
                                   "    border: 2px solid rgb(34, 34, 34);\n"
                                   "    color: rgb(34, 34, 34);\n"
                                   "}\n"
                                   "#frame_6 QPushButton:pressed{\n"
                                   "    background-color: rgb(210, 225, 255);\n"
                                   "    padding-left:3px;\n"
                                   "    padding-top:3px;\n"
                                   "}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 1. 实验流程
        self.pushButton_macro_guidance = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_macro_guidance.setText("实验流程")
        self.pushButton_macro_guidance.setObjectName("pushButton_macro_guidance")
        self.verticalLayout_2.addWidget(self.pushButton_macro_guidance)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        
        # 2. 端口设置
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_setting = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.horizontalLayout_11.addWidget(self.pushButton_setting)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        
        # 3. 练习试次
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_exercise = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_exercise.setFont(font)
        self.pushButton_exercise.setIconSize(QtCore.QSize(5, 16))
        self.pushButton_exercise.setObjectName("pushButton_exercise")
        self.horizontalLayout_8.addWidget(self.pushButton_exercise)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        
        # 4. 正式实验
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_main = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_main.setObjectName("pushButton_main")
        self.horizontalLayout_9.addWidget(self.pushButton_main)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        
        # 5. 数据查看
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_data = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_data.setObjectName("pushButton_data")
        self.horizontalLayout_12.addWidget(self.pushButton_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        
        # 6. 最好成绩
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_highestscore = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_highestscore.setObjectName("pushButton_highestscore")
        self.horizontalLayout_10.addWidget(self.pushButton_highestscore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
                                   "\n"
                                   "    background-color: rgb(255, 255, 255);\n"
                                   "    border-bottom-right-radius:8px;\n"
                                   "    border: 1px solid rgb(240, 240, 240);\n"
                                   "}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("QLabel{\n"
                                         "    border:none;\n"
                                         "    color: rgb(51, 51, 51);\n"
                                         "    font: 50pt \"微软雅黑\";\n"
                                         "}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # 添加介绍界面内容 - 调整居中位置
        self.label_welcome_title = QtWidgets.QLabel(self.page_home)
        self.label_welcome_title.setGeometry(QtCore.QRect(250, 80, 600, 80))
        self.label_welcome_title.setStyleSheet("""
            QLabel {
                font: bold 40pt "微软雅黑";
                color: rgb(51, 51, 51);
                text-align: center;
                border: none;
            }
        """)
        self.label_welcome_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome_title.setObjectName("label_welcome_title")

        self.label_welcome_subtitle = QtWidgets.QLabel(self.page_home)
        self.label_welcome_subtitle.setGeometry(QtCore.QRect(200, 170, 700, 50))
        self.label_welcome_subtitle.setStyleSheet("""
            QLabel {
                font: 24pt "微软雅黑";
                color: rgb(100, 100, 100);
                text-align: center;
                border: none;
            }
        """)
        self.label_welcome_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome_subtitle.setObjectName("label_welcome_subtitle")

        # 实验流程指导框 - 在右侧内容区域居中
        self.frame_guidance = QtWidgets.QFrame(self.page_home)
        self.frame_guidance.setGeometry(QtCore.QRect(50, 250, 1000, 350))
        self.frame_guidance.setStyleSheet("""
            QFrame {
                background-color: rgb(252, 253, 254);
                border: 2px solid rgb(180, 180, 180);
                border-radius: 12px;
            }
        """)
        self.frame_guidance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_guidance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_guidance.setObjectName("frame_guidance")

        self.label_guidance = QtWidgets.QLabel(self.frame_guidance)
        self.label_guidance.setGeometry(QtCore.QRect(50, 250, 900, 80))
        self.label_guidance.setStyleSheet("""
            QLabel {
                font: bold 30pt "微软雅黑";
                color: rgb(51, 51, 51);
                text-align: center;
                border: none;
                line-height: 1.5;
            }
        """)
        self.label_guidance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_guidance.setWordWrap(True)
        self.label_guidance.setObjectName("label_guidance")

        # 添加流程图标 - 在1000px宽框架中居中分布
        self.label_step1 = QtWidgets.QLabel(self.frame_guidance)
        self.label_step1.setGeometry(QtCore.QRect(80, 60, 200, 160))
        self.label_step1.setStyleSheet("""
            QLabel {
                font: bold 24pt "微软雅黑";
                color: rgb(255, 255, 255);
                background-color: rgb(79, 79, 79);
                border-radius: 40px;
                text-align: center;
                border: none;
            }
        """)
        self.label_step1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step1.setText("① 端口设置")
        self.label_step1.setObjectName("label_step1")

        self.label_arrow1 = QtWidgets.QLabel(self.frame_guidance)
        self.label_arrow1.setGeometry(QtCore.QRect(290, 100, 70, 80))
        self.label_arrow1.setStyleSheet("""
            QLabel {
                font: bold 36pt "微软雅黑";
                color: rgb(79, 79, 79);
                text-align: center;
                border: none;
            }
        """)
        self.label_arrow1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arrow1.setText("→")
        self.label_arrow1.setObjectName("label_arrow1")

        self.label_step2 = QtWidgets.QLabel(self.frame_guidance)
        self.label_step2.setGeometry(QtCore.QRect(370, 60, 200, 160))
        self.label_step2.setStyleSheet("""
            QLabel {
                font: bold 24pt "微软雅黑";
                color: rgb(255, 255, 255);
                background-color: rgb(79, 79, 79);
                border-radius: 40px;
                text-align: center;
                border: none;
            }
        """)
        self.label_step2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step2.setText("② 练习试次")
        self.label_step2.setObjectName("label_step2")

        self.label_arrow2 = QtWidgets.QLabel(self.frame_guidance)
        self.label_arrow2.setGeometry(QtCore.QRect(580, 100, 70, 80))
        self.label_arrow2.setStyleSheet("""
            QLabel {
                font: bold 36pt "微软雅黑";
                color: rgb(79, 79, 79);
                text-align: center;
                border: none;
            }
        """)
        self.label_arrow2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_arrow2.setText("→")
        self.label_arrow2.setObjectName("label_arrow2")

        self.label_step3 = QtWidgets.QLabel(self.frame_guidance)
        self.label_step3.setGeometry(QtCore.QRect(660, 60, 200, 160))
        self.label_step3.setStyleSheet("""
            QLabel {
                font: bold 24pt "微软雅黑";
                color: rgb(255, 255, 255);
                background-color: rgb(79, 79, 79);
                border-radius: 40px;
                text-align: center;
                border: none;
            }
        """)
        self.label_step3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step3.setText("③ 正式实验")
        self.label_step3.setObjectName("label_step3")

        # 添加输入法提醒标签到首页
        self.label_input_method_reminder = QtWidgets.QLabel(self.page_home)
        self.label_input_method_reminder.setStyleSheet("QLabel{\n"
                                                       "    border: 2px solid rgb(255, 165, 0);\n"
                                                       "    border-radius: 10px;\n"
                                                       "    background-color: rgb(255, 248, 220);\n"
                                                       "    color: rgb(255, 140, 0);\n"
                                                       "    font: bold 25pt \"微软雅黑\";\n"
                                                       "    padding: 10px;\n"
                                                       "}")
        self.label_input_method_reminder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_method_reminder.setObjectName("label_input_method_reminder")


        self.stackedWidget.addWidget(self.page_home)
        self.page_exercise = QtWidgets.QWidget()
        self.page_exercise.setObjectName("page_exercise")
        self.label_2 = QtWidgets.QLabel(self.page_exercise)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 751, 71))
        self.label_2.setStyleSheet("font-size: 50px")
        self.label_2.setObjectName("label_2")
        self.frame_11 = QtWidgets.QFrame(self.page_exercise)
        self.frame_11.setGeometry(QtCore.QRect(220, 180, 701, 550))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 20, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 110, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 200, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 290, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 380, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(51, 51, 51);\n"
                                         "    color: rgb(51, 51, 51);\n"
                                         "    font: 30pt \"微软雅黑\";\n"
                                         "    border-radius: 8px;\n"
                                         "    padding: 10px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: rgb(245, 245, 245);\n"
                                         "    border: 2px solid rgb(34, 34, 34);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: rgb(230, 230, 230);\n"
                                         "    padding-left:3px;\n"
                                         "    padding-top:3px;\n"
                                         "}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.stackedWidget.addWidget(self.page_exercise)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.run_main_test = QtWidgets.QPushButton(self.page_main)
        self.run_main_test.setGeometry(QtCore.QRect(520, 350, 101, 101))
        self.run_main_test.setStyleSheet("QPushButton{\n"
                                         "    border:none;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "    padding-bottom:20px\n"
                                         "\n"
                                         "}")
        self.run_main_test.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_main_test.setIcon(icon4)
        self.run_main_test.setIconSize(QtCore.QSize(160, 160))
        self.run_main_test.setObjectName("run_main_test")
        self.label_3 = QtWidgets.QLabel(self.page_main)
        self.label_3.setGeometry(QtCore.QRect(300, 220, 511, 71))
        self.label_3.setStyleSheet("font-size: 50px")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_main)
        self.page_highestscore = QtWidgets.QWidget()
        self.page_highestscore.setObjectName("page_highestscore")

        # 标题
        self.title_label = QtWidgets.QLabel(self.page_highestscore)
        self.title_label.setGeometry(QtCore.QRect(300, 30, 500, 60))
        self.title_label.setStyleSheet("""
            QLabel {
                font: bold 32pt "微软雅黑";
                color: rgb(51, 51, 51);
                text-align: center;
                border: none;
            }
        """)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")

        # 排行榜容器
        self.leaderboard_frame = QtWidgets.QFrame(self.page_highestscore)
        self.leaderboard_frame.setGeometry(QtCore.QRect(200, 120, 800, 500))
        self.leaderboard_frame.setStyleSheet("""
            QFrame {
                background-color: rgb(252, 253, 254);
                border: 2px solid rgb(180, 180, 180);
                border-radius: 12px;
            }
        """)
        self.leaderboard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leaderboard_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leaderboard_frame.setObjectName("leaderboard_frame")

        # 表头
        self.header_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.header_frame.setGeometry(QtCore.QRect(20, 20, 760, 50))
        self.header_frame.setStyleSheet("""
            QFrame {
                background-color: rgb(51, 51, 51);
                border-radius: 8px;
                border: none;
            }
        """)
        self.header_frame.setObjectName("header_frame")

        self.header_rank = QtWidgets.QLabel(self.header_frame)
        self.header_rank.setGeometry(QtCore.QRect(30, 10, 80, 30))
        self.header_rank.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.header_rank.setText("排名")
        self.header_rank.setObjectName("header_rank")

        self.header_user = QtWidgets.QLabel(self.header_frame)
        self.header_user.setGeometry(QtCore.QRect(120, 10, 150, 30))
        self.header_user.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_user.setAlignment(QtCore.Qt.AlignCenter)
        self.header_user.setText("用户")
        self.header_user.setObjectName("header_user")

        self.header_accuracy = QtWidgets.QLabel(self.header_frame)
        self.header_accuracy.setGeometry(QtCore.QRect(280, 10, 120, 30))
        self.header_accuracy.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_accuracy.setAlignment(QtCore.Qt.AlignCenter)
        self.header_accuracy.setText("准确度")
        self.header_accuracy.setObjectName("header_accuracy")

        self.header_time = QtWidgets.QLabel(self.header_frame)
        self.header_time.setGeometry(QtCore.QRect(410, 10, 120, 30))
        self.header_time.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_time.setAlignment(QtCore.Qt.AlignCenter)
        self.header_time.setText("总用时")
        self.header_time.setObjectName("header_time")

        self.header_deviation = QtWidgets.QLabel(self.header_frame)
        self.header_deviation.setGeometry(QtCore.QRect(540, 10, 120, 30))
        self.header_deviation.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_deviation.setAlignment(QtCore.Qt.AlignCenter)
        self.header_deviation.setText("平均偏差")
        self.header_deviation.setObjectName("header_deviation")

        self.header_date = QtWidgets.QLabel(self.header_frame)
        self.header_date.setGeometry(QtCore.QRect(670, 10, 90, 30))
        self.header_date.setStyleSheet("font: bold 16pt '微软雅黑'; color: white; border: none;")
        self.header_date.setAlignment(QtCore.Qt.AlignCenter)
        self.header_date.setText("日期")
        self.header_date.setObjectName("header_date")

        # 第一名
        self.first_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.first_place_frame.setGeometry(QtCore.QRect(20, 80, 760, 70))
        self.first_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #FFD700, stop:1 #FFA500);
                border: 2px solid #DAA520;
                border-radius: 10px;
            }
        """)
        self.first_place_frame.setObjectName("first_place_frame")

        self.first_rank_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_rank_label.setGeometry(QtCore.QRect(30, 5, 80, 30))
        self.first_rank_label.setFixedSize(60,60)
        self.first_rank_label.setStyleSheet("font: bold 20pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_rank_label.setObjectName("first_rank_label")

        self.first_user_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_user_label.setGeometry(QtCore.QRect(120, 20, 150, 30))
        self.first_user_label.setStyleSheet("font: bold 16pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_user_label.setObjectName("first_user_label")

        self.first_accuracy_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_accuracy_label.setGeometry(QtCore.QRect(280, 20, 120, 30))
        self.first_accuracy_label.setStyleSheet("font: bold 14pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_accuracy_label.setObjectName("first_accuracy_label")

        self.first_time_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_time_label.setGeometry(QtCore.QRect(410, 20, 120, 30))
        self.first_time_label.setStyleSheet("font: bold 14pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_time_label.setObjectName("first_time_label")

        self.first_deviation_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_deviation_label.setGeometry(QtCore.QRect(540, 20, 120, 30))
        self.first_deviation_label.setStyleSheet("font: bold 14pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_deviation_label.setObjectName("first_deviation_label")

        self.first_date_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_date_label.setGeometry(QtCore.QRect(670, 20, 90, 30))
        self.first_date_label.setStyleSheet("font: bold 12pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.first_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_date_label.setObjectName("first_date_label")

        # 第二名
        self.second_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.second_place_frame.setGeometry(QtCore.QRect(20, 160, 760, 70))
        self.second_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #C0C0C0, stop:1 #A9A9A9);
                border: 2px solid #808080;
                border-radius: 10px;
            }
        """)
        self.second_place_frame.setObjectName("second_place_frame")

        self.second_rank_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_rank_label.setGeometry(QtCore.QRect(30, 5, 80, 30))
        self.second_rank_label.setFixedSize(60, 60)
        self.second_rank_label.setStyleSheet("font: bold 18pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_rank_label.setObjectName("second_rank_label")

        self.second_user_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_user_label.setGeometry(QtCore.QRect(120, 20, 150, 30))
        self.second_user_label.setStyleSheet("font: bold 14pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_user_label.setObjectName("second_user_label")

        self.second_accuracy_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_accuracy_label.setGeometry(QtCore.QRect(280, 20, 120, 30))
        self.second_accuracy_label.setStyleSheet("font: bold 12pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_accuracy_label.setObjectName("second_accuracy_label")

        self.second_time_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_time_label.setGeometry(QtCore.QRect(410, 20, 120, 30))
        self.second_time_label.setStyleSheet("font: bold 12pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_time_label.setObjectName("second_time_label")

        self.second_deviation_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_deviation_label.setGeometry(QtCore.QRect(540, 20, 120, 30))
        self.second_deviation_label.setStyleSheet("font: bold 12pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_deviation_label.setObjectName("second_deviation_label")

        self.second_date_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_date_label.setGeometry(QtCore.QRect(670, 20, 90, 30))
        self.second_date_label.setStyleSheet("font: bold 11pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.second_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_date_label.setObjectName("second_date_label")

        # 第三名
        self.third_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.third_place_frame.setGeometry(QtCore.QRect(20, 240, 760, 70))
        self.third_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #CD7F32, stop:1 #B8860B);
                border: 2px solid #8B4513;
                border-radius: 10px;
            }
        """)
        self.third_place_frame.setObjectName("third_place_frame")

        self.third_rank_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_rank_label.setGeometry(QtCore.QRect(30, 5, 80, 30))
        self.third_rank_label.setFixedSize(60, 60)
        self.third_rank_label.setStyleSheet("QLabel{font: bold 16pt '微软雅黑'; color: #FFFAF0; border: none;}")
        self.third_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_rank_label.setObjectName("third_rank_label")

        self.third_user_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_user_label.setGeometry(QtCore.QRect(120, 20, 150, 30))
        self.third_user_label.setStyleSheet("font: bold 12pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.third_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_user_label.setObjectName("third_user_label")

        self.third_accuracy_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_accuracy_label.setGeometry(QtCore.QRect(280, 20, 120, 30))
        self.third_accuracy_label.setStyleSheet("font: bold 11pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.third_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_accuracy_label.setObjectName("third_accuracy_label")

        self.third_time_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_time_label.setGeometry(QtCore.QRect(410, 20, 120, 30))
        self.third_time_label.setStyleSheet("font: bold 11pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.third_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_time_label.setObjectName("third_time_label")

        self.third_deviation_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_deviation_label.setGeometry(QtCore.QRect(540, 20, 120, 30))
        self.third_deviation_label.setStyleSheet("font: bold 11pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.third_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_deviation_label.setObjectName("third_deviation_label")

        self.third_date_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_date_label.setGeometry(QtCore.QRect(670, 20, 90, 30))
        self.third_date_label.setStyleSheet("font: bold 10pt '微软雅黑'; color: #FFFAF0; border: none;")
        self.third_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_date_label.setObjectName("third_date_label")

        # 底部说明
        self.info_label = QtWidgets.QLabel(self.page_highestscore)
        self.info_label.setGeometry(QtCore.QRect(200, 630, 600, 40))
        self.info_label.setStyleSheet("""
            QLabel {
                font: 14pt "微软雅黑";
                color: rgb(79, 79, 79);
                text-align: center;
                border: none;
            }
        """)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.stackedWidget.addWidget(self.page_highestscore)
        self.page_data = QtWidgets.QWidget()
        self.page_data.setObjectName("page_data")
        self.data_check = QtWidgets.QPushButton(self.page_data)
        self.data_check.setGeometry(QtCore.QRect(520, 350, 141, 131))
        self.data_check.setStyleSheet("QPushButton{\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    padding-bottom:20px\n"
                                      "\n"
                                      "}")
        self.data_check.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_check.setIcon(icon5)
        self.data_check.setIconSize(QtCore.QSize(150, 150))
        self.data_check.setObjectName("data_check")
        self.label_4 = QtWidgets.QLabel(self.page_data)
        self.label_4.setGeometry(QtCore.QRect(300, 220, 511, 71))
        self.label_4.setStyleSheet("font-size: 50px")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_data)
        self.page_serial = QtWidgets.QWidget()
        self.page_serial.setObjectName("page_serial")
        self.frame_8 = QtWidgets.QFrame(self.page_serial)
        self.frame_8.setGeometry(QtCore.QRect(130, 120, 801, 551))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        # 当前端口显示标签
        self.label_current_port_title = QtWidgets.QLabel(self.frame_8)
        self.label_current_port_title.setGeometry(QtCore.QRect(50, 50, 200, 60))
        self.label_current_port_title.setStyleSheet("""
            QLabel {
                font: bold 28pt "微软雅黑";
                color: rgb(51, 51, 51);
                border: none;
            }
        """)
        self.label_current_port_title.setText("当前端口:")
        self.label_current_port_title.setObjectName("label_current_port_title")

        self.label_current_port = QtWidgets.QLabel(self.frame_8)
        self.label_current_port.setGeometry(QtCore.QRect(260, 50, 300, 60))
        self.label_current_port.setStyleSheet("""
            QLabel {
                font: bold 24pt "微软雅黑";
                color: rgb(255, 0, 0);
                border: 2px solid rgb(200, 200, 200);
                border-radius: 10px;
                background-color: rgb(248, 248, 248);
                padding: 10px;
            }
        """)
        self.label_current_port.setText("未检测")
        self.label_current_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_current_port.setObjectName("label_current_port")

        # 获取脑电端口按钮
        self.pushButton_detect_port = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_detect_port.setGeometry(QtCore.QRect(580, 50, 180, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_detect_port.setFont(font)
        self.pushButton_detect_port.setStyleSheet("""
            QPushButton {
                background-color: rgb(255, 255, 255);
                border: 2px solid rgb(51, 51, 51);
                color: rgb(51, 51, 51);
                font: 20pt "微软雅黑";
                border-radius: 8px;
                padding: 8px;
            }
            QPushButton:hover {
                background-color: rgb(245, 245, 245);
                border: 2px solid rgb(34, 34, 34);
            }
            QPushButton:pressed {
                background-color: rgb(230, 230, 230);
                padding-left: 3px;
                padding-top: 3px;
            }
        """)
        self.pushButton_detect_port.setText("获取脑电端口")
        self.pushButton_detect_port.setObjectName("pushButton_detect_port")

        # 状态指示灯（调整位置）
        self.label_connection_status = QtWidgets.QLabel(self.frame_8)
        self.label_connection_status.setGeometry(QtCore.QRect(330, 150, 140, 140))
        self.label_connection_status.setStyleSheet("""
            QLabel {
                border: 3px solid rgb(100, 100, 100);
                border-radius: 70px;
                background-color: rgb(144, 144, 144);
            }
        """)
        self.label_connection_status.setText("")
        self.label_connection_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_connection_status.setObjectName("label_connection_status")

        self.label_status_text = QtWidgets.QLabel(self.frame_8)
        self.label_status_text.setGeometry(QtCore.QRect(300, 300, 200, 50))
        self.label_status_text.setStyleSheet("""
            QLabel {
                border: none;
                color: rgb(255, 0, 0);
                font: 24pt "微软雅黑";
            }
        """)
        self.label_status_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_text.setObjectName("label_status_text")

        # 确认按钮（发送marker8）
        self.pushButton_send_marker = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_send_marker.setGeometry(QtCore.QRect(300, 400, 200, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_send_marker.setFont(font)
        self.pushButton_send_marker.setStyleSheet("""
            QPushButton {
                background-color: rgb(255, 255, 255);
                border: 2px solid rgb(46, 204, 113);
                color: rgb(46, 204, 113);
                font: 24pt "微软雅黑";
                border-radius: 8px;
                padding: 8px;
            }
            QPushButton:hover {
                background-color: rgb(240, 255, 240);
                border: 2px solid rgb(39, 174, 96);
                color: rgb(39, 174, 96);
            }
            QPushButton:pressed {
                background-color: rgb(220, 255, 220);
                padding-left: 3px;
                padding-top: 3px;
            }
            QPushButton:disabled {
                background-color: rgb(245, 245, 245);
                border: 2px solid rgb(200, 200, 200);
                color: rgb(150, 150, 150);
            }
        """)
        self.pushButton_send_marker.setText("确认连接")
        self.pushButton_send_marker.setEnabled(False)  # 默认禁用
        self.pushButton_send_marker.setObjectName("pushButton_send_marker")
        self.stackedWidget.addWidget(self.page_serial)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        
        # 设置提醒标签位置在首页，确保不遮挡指导语 - 调整居中
        self.label_input_method_reminder.setGeometry(QtCore.QRect(150, 620, 800, 60))
        
        self.pushButton_2.clicked.connect(MainWindow.close)  # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "user"))
        self.pushButton_relogin.setText(_translate("MainWindow", ""))
        self.pushButton_relogin.setStyleSheet("QPushButton {\
        image: url(:/image/exit.png);\
        background-color: transparent;\
        color:  #2c3e50;\
        border: none;\
        padding: 8px 12px;\
        }QPushButton:hover {\
        color: #42b983;  /* Vue风格的悬停颜色 */\
    }\
    QPushButton:pressed {\
        color: #2d8d62;  /* 按下时更深的颜色 */\
        padding-left: 13px;  /* 向右移动1像素 */\
        padding-top: 9px;    /* 向下移动1像素 */\
    }")

        self.pushButton_exercise.setText(_translate("MainWindow", "练习试次"))
        self.pushButton_main.setText(_translate("MainWindow", "正式实验"))
        self.pushButton_highestscore.setText(_translate("MainWindow", "最好成绩"))
        self.pushButton_data.setText(_translate("MainWindow", "数据查看"))
        self.pushButton_setting.setText(_translate("MainWindow", "端口设置"))
        self.label_welcome_title.setText(_translate("MainWindow", "欢迎使用实验系统"))
        self.label_welcome_subtitle.setText(_translate("MainWindow", "请遵循以下实验流程"))

        self.label_2.setText(_translate("MainWindow", "点击进入对应训练模块"))
        self.pushButton_4.setText(_translate("MainWindow", "人员①绘图练习模块"))
        self.pushButton_5.setText(_translate("MainWindow", "人员②绘图练习模块"))
        self.pushButton_6.setText(_translate("MainWindow", "人员③绘图练习模块"))
        self.pushButton_9.setText(_translate("MainWindow", "人员①&人员②绘图练习模块"))
        self.pushButton_10.setText(_translate("MainWindow", "人员①&人员③绘图练习模块"))
        self.label_3.setText(_translate("MainWindow", "点击按钮进行正式实验"))
        self.title_label.setText(_translate("MainWindow", "🏆 准确度排行榜 TOP 3"))
        # self.first_rank_label.setText(_translate("MainWindow", "🥇"))
        self.first_rank_label.setStyleSheet("QLabel { image: url(:/image/1.png); }")
        self.first_user_label.setText(_translate("MainWindow", "用户"))
        self.first_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.first_time_label.setText(_translate("MainWindow", "用时: -"))
        self.first_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.first_date_label.setText(_translate("MainWindow", "日期: -"))
        # self.second_rank_label.setText(_translate("MainWindow", "🥈"))
        self.second_rank_label.setStyleSheet("QLabel { image: url(:/image/2.png); }")
        self.second_user_label.setText(_translate("MainWindow", "用户"))
        self.second_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.second_time_label.setText(_translate("MainWindow", "用时: -"))
        self.second_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.second_date_label.setText(_translate("MainWindow", "日期: -"))
        # self.third_rank_label.setText(_translate("MainWindow", "🥉"))
        self.third_rank_label.setStyleSheet("QLabel { image: url(:/image/3.png); }")
        self.third_user_label.setText(_translate("MainWindow", "用户"))
        self.third_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.third_time_label.setText(_translate("MainWindow", "用时: -"))
        self.third_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.third_date_label.setText(_translate("MainWindow", "日期: -"))
        self.info_label.setText(_translate("MainWindow", "💡 排名基于准确度高低，偏差面积越小越好，用时越短越好"))
        self.label_4.setText(_translate("MainWindow", "点击按钮查看行为数据"))
        self.label_input_method_reminder.setText(_translate("MainWindow", "⚠️提醒：请确保切换到英文输入法"))
        self.pushButton_macro_guidance.setText(_translate("MainWindow", "实验流程"))
        self.label_status_text.setText(_translate("MainWindow", "未连接"))


from src.utils import resouce_rc
