# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .ui.res import res


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 简化全屏设置
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # 注释掉半透明背景，可能影响全屏显示
        # MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 设置centralwidget为MainWindow的中心部件
        MainWindow.setCentralWidget(self.centralwidget)
        
        # 创建主布局管理器
        main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        main_layout.setContentsMargins(10, 10, 10, 10)  # 进一步减少边距
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        # 移除固定尺寸设置，让布局管理器处理
        # self.frame.setGeometry(QtCore.QRect(50, 50, 1820, 980))
        # self.frame.setMinimumSize(QtCore.QSize(1820, 980))
        
        # 将frame添加到布局中
        main_layout.addWidget(self.frame)
        self.frame.setStyleSheet("#frame{\n"
                                 "\n"
                                 "    background-color: rgb(248, 249, 250);\n"
                                 "    border: 1px solid rgb(200, 200, 200);\n"
                                 "    border-radius: 8px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(248, 249, 250);\n"
                                   "border-top-left-radius:8px;\n"
                                   "border-top-right-radius:8px;\n"
                                   "border-bottom: 1px solid rgb(220, 220, 220);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:none;\n"
                                      "font: 20pt \"微软雅黑\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/地球.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2.addWidget(self.frame_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        # self.pushButton_relogin = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_relogin = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_relogin.setFont(font)
        self.pushButton_relogin.setStyleSheet("QPushButton{\n"
                                   "    border:none;\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    padding-bottom:10px\n"
                                   "\n"
                                   "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_relogin.setIcon(icon1)
        self.pushButton_relogin.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_relogin.setObjectName("pushButton_relogin")
        self.horizontalLayout_2.addWidget(self.pushButton_relogin)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
                                   "    border:none;\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "    padding-bottom:10px\n"
                                   "\n"
                                   "}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minimize (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_relogin)
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")

        self.horizontalLayout_3.addWidget(self.pushButton_2)

        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
                                   "\n"
                                   "    background-color: rgb(240, 242, 245);\n"
                                   "    border-bottom-left-radius:8px;\n"
                                   "    border-top-right-radius:8px;\n"
                                   "    border-right: 1px solid rgb(220, 220, 220);\n"
                                   "}\n"
                                   "#frame_6 QPushButton{\n"
                                   "    background-color: rgb(255, 255, 255);\n"
                                   "    border: 2px solid rgb(51, 51, 51);\n"
                                   "    color: rgb(51, 51, 51);\n"
                                   "    font: 50pt \"微软雅黑\";\n"
                                   "    border-radius: 8px;\n"
                                   "    padding: 10px;\n"
                                   "    margin: 5px;\n"
                                   "}\n"
                                   "#frame_6 QPushButton:hover{\n"
                                   "    background-color: rgb(230, 240, 255);\n"
                                   "    border: 2px solid rgb(34, 34, 34);\n"
                                   "    color: rgb(34, 34, 34);\n"
                                   "}\n"
                                   "#frame_6 QPushButton:pressed{\n"
                                   "    background-color: rgb(210, 225, 255);\n"
                                   "    padding-left:3px;\n"
                                   "    padding-top:3px;\n"
                                   "}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 1. 实验介绍
        self.pushButton_macro_guidance = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_macro_guidance.setText("实验介绍")
        self.pushButton_macro_guidance.setObjectName("pushButton_macro_guidance")
        self.verticalLayout_2.addWidget(self.pushButton_macro_guidance)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)

        # 2. 练习试次
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_exercise = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_exercise.setFont(font)
        self.pushButton_exercise.setIconSize(QtCore.QSize(5, 16))
        self.pushButton_exercise.setObjectName("pushButton_exercise")
        self.horizontalLayout_8.addWidget(self.pushButton_exercise)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)

        # 3. 正式实验
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_main = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_main.setObjectName("pushButton_main")
        self.horizontalLayout_9.addWidget(self.pushButton_main)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        # 4. 数据查看
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_data = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_data.setObjectName("pushButton_data")
        self.horizontalLayout_12.addWidget(self.pushButton_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)

        # 5. 最好成绩
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_highestscore = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_highestscore.setObjectName("pushButton_highestscore")
        self.horizontalLayout_10.addWidget(self.pushButton_highestscore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        # 6. 端口设置 - 已注释，功能保留
        # self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        # self.pushButton_setting = QtWidgets.QPushButton(self.frame_6)
        # self.pushButton_setting.setObjectName("pushButton_setting")
        # self.horizontalLayout_11.addWidget(self.pushButton_setting)
        # self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        # spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
                                   "\n"
                                   "    background-color: rgb(255, 255, 255);\n"
                                   "    border-bottom-right-radius:8px;\n"
                                   "    border: 1px solid rgb(240, 240, 240);\n"
                                   "}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("QLabel{\n"
                                         "    border:none;\n"
                                         "    color: rgb(51, 51, 51);\n"
                                         "    font: 50pt \"微软雅黑\";\n"
                                         "}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_4.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # <<< MODIFICATION START >>>
        # --- Using layout managers for responsive design ---

        # 欢迎标题
        self.label_welcome_subtitle = QtWidgets.QLabel(self.page_home)
        self.label_welcome_subtitle.setStyleSheet("""
            QLabel {
                font: 24pt "微软雅黑";
                color: rgb(100, 100, 100);
                text-align: center;
                border: none;
            }
        """)
        self.label_welcome_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome_subtitle.setObjectName("label_welcome_subtitle")
        self.verticalLayout_4.addWidget(self.label_welcome_subtitle)

        # 实验介绍内容框
        self.frame_introduction = QtWidgets.QFrame(self.page_home)
        self.frame_introduction.setMinimumHeight(130)
        self.frame_introduction.setMaximumHeight(180)
        self.frame_introduction.setStyleSheet("""
            QFrame {
                background-color: rgb(252, 253, 254);
                border: 2px solid rgb(220, 220, 220);
                border-radius: 12px;
            }
        """)
        self.frame_introduction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_introduction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_introduction.setObjectName("frame_introduction")
        
        # 给介绍框添加布局
        intro_layout = QtWidgets.QVBoxLayout(self.frame_introduction)
        intro_layout.setContentsMargins(30, 15, 30, 15)
        
        # 实验介绍内容
        self.label_intro_content = QtWidgets.QLabel(self.frame_introduction)
        self.label_intro_content.setStyleSheet("""
            QLabel {
                font: 18pt "微软雅黑";
                color: rgb(51, 51, 51);
                border: none;
            }
        """)
        self.label_intro_content.setTextFormat(QtCore.Qt.RichText)
        self.label_intro_content.setAlignment(QtCore.Qt.AlignTop | QtCore.Qt.AlignLeft)
        self.label_intro_content.setWordWrap(True)
        self.label_intro_content.setObjectName("label_intro_content")
        intro_layout.addWidget(self.label_intro_content)
        
        self.verticalLayout_4.addWidget(self.frame_introduction)

        # 任务图示
        self.label_task_image = QtWidgets.QLabel(self.page_home)
        self.label_task_image.setMinimumHeight(300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_task_image.sizePolicy().hasHeightForWidth())
        self.label_task_image.setSizePolicy(sizePolicy)
        self.label_task_image.setAlignment(QtCore.Qt.AlignCenter)
        # IMPORTANT: Replace with your actual image path from resources
        pixmap = QtGui.QPixmap(":/image/task.png")
        self.label_task_image.setScaledContents(False)
        if pixmap.isNull():
            self.label_task_image.setText("任务图示 (请在 res.qrc 中添加图片)")
        else:
            self.label_task_image.setPixmap(
                pixmap.scaled(self.label_task_image.size(), QtCore.Qt.KeepAspectRatio, QtCore.Qt.SmoothTransformation))
        self.label_task_image.setObjectName("label_task_image")
        self.verticalLayout_4.addWidget(self.label_task_image)

        # 输入法提醒标签
        self.label_input_method_reminder = QtWidgets.QLabel(self.page_home)
        self.label_input_method_reminder.setMinimumHeight(60)
        self.label_input_method_reminder.setMaximumHeight(80)
        self.label_input_method_reminder.setStyleSheet("QLabel{\n"
                                                       "    border: 2px solid rgb(255, 165, 0);\n"
                                                       "    border-radius: 10px;\n"
                                                       "    background-color: rgb(255, 248, 220);\n"
                                                       "    color: rgb(255, 140, 0);\n"
                                                       "    font: bold 25pt \"微软雅黑\";\n"
                                                       "    padding: 10px;\n"
                                                       "}")
        self.label_input_method_reminder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_method_reminder.setObjectName("label_input_method_reminder")
        self.verticalLayout_4.addWidget(self.label_input_method_reminder)

        # <<< MODIFICATION END >>>

        self.stackedWidget.addWidget(self.page_home)
        self.page_exercise = QtWidgets.QWidget()
        self.page_exercise.setObjectName("page_exercise")
        
        # 为 page_exercise 添加布局
        exercise_layout = QtWidgets.QVBoxLayout(self.page_exercise)
        exercise_layout.setContentsMargins(50, 40, 50, 40)
        exercise_layout.setSpacing(30)
        
        self.label_2 = QtWidgets.QLabel(self.page_exercise)
        self.label_2.setStyleSheet("font-size: 50px")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        exercise_layout.addWidget(self.label_2)
        
        self.frame_11 = QtWidgets.QFrame(self.page_exercise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        
        # 为 frame_11 添加布局
        frame11_layout = QtWidgets.QVBoxLayout(self.frame_11)
        frame11_layout.setContentsMargins(20, 30, 20, 30)
        frame11_layout.setSpacing(30)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_4.setMinimumHeight(80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        frame11_layout.addWidget(self.pushButton_4)
        
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_9.setMinimumHeight(80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(51, 51, 51);\n"
                                        "    color: rgb(51, 51, 51);\n"
                                        "    font: 30pt \"微软雅黑\";\n"
                                        "    border-radius: 8px;\n"
                                        "    padding: 10px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(245, 245, 245);\n"
                                        "    border: 2px solid rgb(34, 34, 34);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "    background-color: rgb(230, 230, 230);\n"
                                        "    padding-left:3px;\n"
                                        "    padding-top:3px;\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        frame11_layout.addWidget(self.pushButton_9)
        
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_10.setMinimumHeight(80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(51, 51, 51);\n"
                                         "    color: rgb(51, 51, 51);\n"
                                         "    font: 30pt \"微软雅黑\";\n"
                                         "    border-radius: 8px;\n"
                                         "    padding: 10px;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "    background-color: rgb(245, 245, 245);\n"
                                         "    border: 2px solid rgb(34, 34, 34);\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "    background-color: rgb(230, 230, 230);\n"
                                         "    padding-left:3px;\n"
                                         "    padding-top:3px;\n"
                                         "}")
        self.pushButton_10.setObjectName("pushButton_10")
        frame11_layout.addWidget(self.pushButton_10)
        
        # 添加伸缩项目填充剩余空间
        spacerItem_exercise = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        frame11_layout.addItem(spacerItem_exercise)
        
        exercise_layout.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.page_exercise)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        
        # 为 page_main 添加布局
        main_layout = QtWidgets.QVBoxLayout(self.page_main)
        main_layout.setContentsMargins(50, 50, 50, 50)
        main_layout.setSpacing(30)
        
        # 添加上方空白
        spacerItem_top = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        main_layout.addItem(spacerItem_top)
        
        self.label_3 = QtWidgets.QLabel(self.page_main)
        self.label_3.setStyleSheet("font-size: 50px")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        main_layout.addWidget(self.label_3)
        
        self.run_main_test = QtWidgets.QPushButton(self.page_main)
        self.run_main_test.setMinimumSize(QtCore.QSize(160, 160))
        self.run_main_test.setMaximumSize(QtCore.QSize(200, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_main_test.sizePolicy().hasHeightForWidth())
        self.run_main_test.setSizePolicy(sizePolicy)
        self.run_main_test.setStyleSheet("QPushButton{\n"
                                         "    border:none;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "    padding-bottom:20px\n"
                                         "\n"
                                         "}")
        self.run_main_test.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_main_test.setIcon(icon4)
        self.run_main_test.setIconSize(QtCore.QSize(160, 160))
        self.run_main_test.setObjectName("run_main_test")
        
        # 创建水平布局居中按钮
        button_layout = QtWidgets.QHBoxLayout()
        button_layout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum))
        button_layout.addWidget(self.run_main_test)
        button_layout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum))
        main_layout.addLayout(button_layout)
        
        # 添加下方空白
        spacerItem_bottom = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        main_layout.addItem(spacerItem_bottom)
        self.stackedWidget.addWidget(self.page_main)
        self.page_highestscore = QtWidgets.QWidget()
        self.page_highestscore.setObjectName("page_highestscore")
        
        # 为排行榜页面创建主布局
        highestscore_layout = QtWidgets.QVBoxLayout(self.page_highestscore)
        highestscore_layout.setContentsMargins(30, 30, 30, 30)
        highestscore_layout.setSpacing(20)

        # 标题
        self.title_label = QtWidgets.QLabel(self.page_highestscore)
        self.title_label.setMinimumHeight(80)
        self.title_label.setStyleSheet("""
            QLabel {
                font: bold 40pt "微软雅黑";
                color: rgb(51, 51, 51);
                text-align: center;
                border: none;
            }
        """)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        highestscore_layout.addWidget(self.title_label)

        # 排行榜容器 - 使用布局管理器铺满剩余空间
        self.leaderboard_frame = QtWidgets.QFrame(self.page_highestscore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.leaderboard_frame.sizePolicy().hasHeightForWidth())
        self.leaderboard_frame.setSizePolicy(sizePolicy)
        self.leaderboard_frame.setStyleSheet("""
            QFrame {
                background-color: rgb(252, 253, 254);
                border: 2px solid rgb(180, 180, 180);
                border-radius: 12px;
            }
        """)
        self.leaderboard_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leaderboard_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leaderboard_frame.setObjectName("leaderboard_frame")
        
        # 为排行榜容器创建垂直布局
        leaderboard_layout = QtWidgets.QVBoxLayout(self.leaderboard_frame)
        leaderboard_layout.setContentsMargins(30, 30, 30, 30)
        leaderboard_layout.setSpacing(25)

        # 表头
        self.header_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.header_frame.setMinimumHeight(70)
        self.header_frame.setMaximumHeight(80)
        self.header_frame.setStyleSheet("""
            QFrame {
                background-color: rgb(51, 51, 51);
                border-radius: 12px;
                border: none;
            }
        """)
        self.header_frame.setObjectName("header_frame")
        
        # 为表头创建水平布局
        header_layout = QtWidgets.QHBoxLayout(self.header_frame)
        header_layout.setContentsMargins(20, 15, 20, 15)
        header_layout.setSpacing(10)

        self.header_rank = QtWidgets.QLabel(self.header_frame)
        self.header_rank.setStyleSheet("font: bold 24pt '微软雅黑'; color: white; border: none;")
        self.header_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.header_rank.setText("排名")
        self.header_rank.setObjectName("header_rank")
        header_layout.addWidget(self.header_rank, 1)

        self.header_user = QtWidgets.QLabel(self.header_frame)
        self.header_user.setStyleSheet("font: bold 24pt '微软雅黑'; color: white; border: none;")
        self.header_user.setAlignment(QtCore.Qt.AlignCenter)
        self.header_user.setText("用户")
        self.header_user.setObjectName("header_user")
        header_layout.addWidget(self.header_user, 2)

        self.header_accuracy = QtWidgets.QLabel(self.header_frame)
        self.header_accuracy.setStyleSheet("font: bold 24pt '微软雅黑'; color: white; border: none;")
        self.header_accuracy.setAlignment(QtCore.Qt.AlignCenter)
        self.header_accuracy.setText("准确度")
        self.header_accuracy.setObjectName("header_accuracy")
        header_layout.addWidget(self.header_accuracy, 2)

        self.header_time = QtWidgets.QLabel(self.header_frame)
        self.header_time.setStyleSheet("font: bold 24pt '微软雅黑'; color: white; border: none;")
        self.header_time.setAlignment(QtCore.Qt.AlignCenter)
        self.header_time.setText("总用时")
        self.header_time.setObjectName("header_time")
        header_layout.addWidget(self.header_time, 2)

        self.header_deviation = QtWidgets.QLabel(self.header_frame)
        self.header_deviation.setStyleSheet("font: bold 24pt '微软雅黑'; color: white; border: none;")
        self.header_deviation.setAlignment(QtCore.Qt.AlignCenter)
        self.header_deviation.setText("平均偏差")
        self.header_deviation.setObjectName("header_deviation")
        header_layout.addWidget(self.header_deviation, 2)

        self.header_date = QtWidgets.QLabel(self.header_frame)
        self.header_date.setStyleSheet("font: bold 20pt '微软雅黑'; color: white; border: none;")
        self.header_date.setAlignment(QtCore.Qt.AlignCenter)
        self.header_date.setText("日期")
        self.header_date.setObjectName("header_date")
        header_layout.addWidget(self.header_date, 1)
        
        leaderboard_layout.addWidget(self.header_frame)

        # 第一名
        self.first_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.first_place_frame.setMinimumHeight(120)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_place_frame.sizePolicy().hasHeightForWidth())
        self.first_place_frame.setSizePolicy(sizePolicy)
        self.first_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #FFD700, stop:1 #FFA500);
                border: 3px solid #DAA520;
                border-radius: 15px;
            }
        """)
        self.first_place_frame.setObjectName("first_place_frame")
        
        # 为第一名创建水平布局
        first_layout = QtWidgets.QHBoxLayout(self.first_place_frame)
        first_layout.setContentsMargins(20, 20, 20, 20)
        first_layout.setSpacing(10)

        self.first_rank_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_rank_label.setMinimumSize(80, 80)
        self.first_rank_label.setMaximumSize(80, 80)
        self.first_rank_label.setStyleSheet("font: bold 32pt '微软雅黑'; color: #000000; border: none;")
        self.first_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_rank_label.setObjectName("first_rank_label")
        first_layout.addWidget(self.first_rank_label, 0)

        self.first_user_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_user_label.setStyleSheet("font: bold 28pt '微软雅黑'; color: #000000; border: none;")
        self.first_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_user_label.setObjectName("first_user_label")
        first_layout.addWidget(self.first_user_label, 2)

        self.first_accuracy_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_accuracy_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.first_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_accuracy_label.setObjectName("first_accuracy_label")
        first_layout.addWidget(self.first_accuracy_label, 2)

        self.first_time_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_time_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.first_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_time_label.setObjectName("first_time_label")
        first_layout.addWidget(self.first_time_label, 2)

        self.first_deviation_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_deviation_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.first_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_deviation_label.setObjectName("first_deviation_label")
        first_layout.addWidget(self.first_deviation_label, 2)

        self.first_date_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_date_label.setStyleSheet("font: bold 18pt '微软雅黑'; color: #000000; border: none;")
        self.first_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_date_label.setObjectName("first_date_label")
        first_layout.addWidget(self.first_date_label, 1)
        
        leaderboard_layout.addWidget(self.first_place_frame)

        # 第二名
        self.second_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.second_place_frame.setMinimumHeight(110)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.second_place_frame.sizePolicy().hasHeightForWidth())
        self.second_place_frame.setSizePolicy(sizePolicy)
        self.second_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #C0C0C0, stop:1 #A9A9A9);
                border: 3px solid #808080;
                border-radius: 15px;
            }
        """)
        self.second_place_frame.setObjectName("second_place_frame")
        
        # 为第二名创建水平布局
        second_layout = QtWidgets.QHBoxLayout(self.second_place_frame)
        second_layout.setContentsMargins(20, 20, 20, 20)
        second_layout.setSpacing(10)

        self.second_rank_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_rank_label.setMinimumSize(80, 80)
        self.second_rank_label.setMaximumSize(80, 80)
        self.second_rank_label.setStyleSheet("font: bold 32pt '微软雅黑'; color: #000000; border: none;")
        self.second_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_rank_label.setObjectName("second_rank_label")
        second_layout.addWidget(self.second_rank_label, 0)

        self.second_user_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_user_label.setStyleSheet("font: bold 28pt '微软雅黑'; color: #000000; border: none;")
        self.second_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_user_label.setObjectName("second_user_label")
        second_layout.addWidget(self.second_user_label, 2)

        self.second_accuracy_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_accuracy_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.second_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_accuracy_label.setObjectName("second_accuracy_label")
        second_layout.addWidget(self.second_accuracy_label, 2)

        self.second_time_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_time_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.second_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_time_label.setObjectName("second_time_label")
        second_layout.addWidget(self.second_time_label, 2)

        self.second_deviation_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_deviation_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.second_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_deviation_label.setObjectName("second_deviation_label")
        second_layout.addWidget(self.second_deviation_label, 2)

        self.second_date_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_date_label.setStyleSheet("font: bold 18pt '微软雅黑'; color: #000000; border: none;")
        self.second_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.second_date_label.setObjectName("second_date_label")
        second_layout.addWidget(self.second_date_label, 1)
        
        leaderboard_layout.addWidget(self.second_place_frame)

        # 第三名
        self.third_place_frame = QtWidgets.QFrame(self.leaderboard_frame)
        self.third_place_frame.setMinimumHeight(100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.third_place_frame.sizePolicy().hasHeightForWidth())
        self.third_place_frame.setSizePolicy(sizePolicy)
        self.third_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #CD7F32, stop:1 #B8860B);
                border: 3px solid #8B4513;
                border-radius: 15px;
            }
        """)
        self.third_place_frame.setObjectName("third_place_frame")
        
        # 为第三名创建水平布局
        third_layout = QtWidgets.QHBoxLayout(self.third_place_frame)
        third_layout.setContentsMargins(20, 20, 20, 20)
        third_layout.setSpacing(10)

        self.third_rank_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_rank_label.setMinimumSize(80, 80)
        self.third_rank_label.setMaximumSize(80, 80)
        self.third_rank_label.setStyleSheet("QLabel{font: bold 32pt '微软雅黑'; color: #000000; border: none;}")
        self.third_rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_rank_label.setObjectName("third_rank_label")
        third_layout.addWidget(self.third_rank_label, 0)

        self.third_user_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_user_label.setStyleSheet("font: bold 28pt '微软雅黑'; color: #000000; border: none;")
        self.third_user_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_user_label.setObjectName("third_user_label")
        third_layout.addWidget(self.third_user_label, 2)

        self.third_accuracy_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_accuracy_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.third_accuracy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_accuracy_label.setObjectName("third_accuracy_label")
        third_layout.addWidget(self.third_accuracy_label, 2)

        self.third_time_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_time_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.third_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_time_label.setObjectName("third_time_label")
        third_layout.addWidget(self.third_time_label, 2)

        self.third_deviation_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_deviation_label.setStyleSheet("font: bold 22pt '微软雅黑'; color: #000000; border: none;")
        self.third_deviation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_deviation_label.setObjectName("third_deviation_label")
        third_layout.addWidget(self.third_deviation_label, 2)

        self.third_date_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_date_label.setStyleSheet("font: bold 18pt '微软雅黑'; color: #000000; border: none;")
        self.third_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.third_date_label.setObjectName("third_date_label")
        third_layout.addWidget(self.third_date_label, 1)
        
        leaderboard_layout.addWidget(self.third_place_frame)

        # 添加伸缩空间，让排行榜框架占满剩余空间
        spacerItem_leaderboard = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        leaderboard_layout.addItem(spacerItem_leaderboard)
        
        highestscore_layout.addWidget(self.leaderboard_frame)
        
        # 底部说明
        self.info_label = QtWidgets.QLabel(self.page_highestscore)
        self.info_label.setMinimumHeight(50)
        self.info_label.setStyleSheet("""
            QLabel {
                font: 20pt "微软雅黑";
                color: rgb(79, 79, 79);
                text-align: center;
                border: none;
            }
        """)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        highestscore_layout.addWidget(self.info_label)
        self.stackedWidget.addWidget(self.page_highestscore)
        self.page_data = QtWidgets.QWidget()
        self.page_data.setObjectName("page_data")
        
        # 为 page_data 添加布局
        data_layout = QtWidgets.QVBoxLayout(self.page_data)
        data_layout.setContentsMargins(50, 50, 50, 50)
        data_layout.setSpacing(30)
        
        # 添加上方空白
        spacerItem_data_top = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        data_layout.addItem(spacerItem_data_top)
        
        self.label_4 = QtWidgets.QLabel(self.page_data)
        self.label_4.setStyleSheet("font-size: 50px")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        data_layout.addWidget(self.label_4)
        
        self.data_check = QtWidgets.QPushButton(self.page_data)
        self.data_check.setMinimumSize(QtCore.QSize(150, 150))
        self.data_check.setMaximumSize(QtCore.QSize(200, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_check.sizePolicy().hasHeightForWidth())
        self.data_check.setSizePolicy(sizePolicy)
        self.data_check.setStyleSheet("QPushButton{\n"
                                      "    border:none;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover{\n"
                                      "    padding-bottom:20px\n"
                                      "\n"
                                      "}")
        self.data_check.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_check.setIcon(icon5)
        self.data_check.setIconSize(QtCore.QSize(150, 150))
        self.data_check.setObjectName("data_check")
        
        # 创建水平布局居中按钮
        data_button_layout = QtWidgets.QHBoxLayout()
        data_button_layout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum))
        data_button_layout.addWidget(self.data_check)
        data_button_layout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum))
        data_layout.addLayout(data_button_layout)
        
        # 添加下方空白
        spacerItem_data_bottom = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        data_layout.addItem(spacerItem_data_bottom)
        self.stackedWidget.addWidget(self.page_data)
        self.page_serial = QtWidgets.QWidget()
        self.page_serial.setObjectName("page_serial")
        self.frame_8 = QtWidgets.QFrame(self.page_serial)
        self.frame_8.setGeometry(QtCore.QRect(130, 120, 801, 551))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        # 当前端口显示标签
        self.label_current_port_title = QtWidgets.QLabel(self.frame_8)
        self.label_current_port_title.setGeometry(QtCore.QRect(50, 50, 200, 60))
        self.label_current_port_title.setStyleSheet("""
            QLabel {
                font: bold 28pt "微软雅黑";
                color: rgb(51, 51, 51);
                border: none;
            }
        """)
        self.label_current_port_title.setText("当前端口:")
        self.label_current_port_title.setObjectName("label_current_port_title")

        self.label_current_port = QtWidgets.QLabel(self.frame_8)
        self.label_current_port.setGeometry(QtCore.QRect(260, 50, 300, 60))
        self.label_current_port.setStyleSheet("""
            QLabel {
                font: bold 24pt "微软雅黑";
                color: rgb(255, 0, 0);
                border: 2px solid rgb(200, 200, 200);
                border-radius: 10px;
                background-color: rgb(248, 248, 248);
                padding: 10px;
            }
        """)
        self.label_current_port.setText("未检测")
        self.label_current_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_current_port.setObjectName("label_current_port")

        # 端口连接按钮（自动检测+连接）
        self.pushButton_auto_connect = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_auto_connect.setGeometry(QtCore.QRect(580, 50, 180, 60))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_auto_connect.setFont(font)
        self.pushButton_auto_connect.setStyleSheet("""
            QPushButton {
                background-color: rgb(255, 255, 255);
                border: 2px solid rgb(51, 51, 51);
                color: rgb(51, 51, 51);
                font: 20pt "微软雅黑";
                border-radius: 8px;
                padding: 8px;
            }
            QPushButton:hover {
                background-color: rgb(245, 245, 245);
                border: 2px solid rgb(34, 34, 34);
            }
            QPushButton:pressed {
                background-color: rgb(230, 230, 230);
                padding-left: 3px;
                padding-top: 3px;
            }
            QPushButton:disabled {
                background-color: rgb(245, 245, 245);
                border: 2px solid rgb(200, 200, 200);
                color: rgb(150, 150, 150);
            }
        """)
        self.pushButton_auto_connect.setText("连接端口")
        self.pushButton_auto_connect.setObjectName("pushButton_auto_connect")

        # 状态指示灯（调整位置）
        self.label_connection_status = QtWidgets.QLabel(self.frame_8)
        self.label_connection_status.setGeometry(QtCore.QRect(330, 150, 140, 140))
        self.label_connection_status.setStyleSheet("""
            QLabel {
                border: 3px solid rgb(100, 100, 100);
                border-radius: 70px;
                background-color: rgb(144, 144, 144);
            }
        """)
        self.label_connection_status.setText("")
        self.label_connection_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_connection_status.setObjectName("label_connection_status")

        self.label_status_text = QtWidgets.QLabel(self.frame_8)
        self.label_status_text.setGeometry(QtCore.QRect(300, 300, 200, 50))
        self.label_status_text.setStyleSheet("""
            QLabel {
                border: none;
                color: rgb(255, 0, 0);
                font: 24pt "微软雅黑";
            }
        """)
        self.label_status_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_text.setObjectName("label_status_text")

        self.stackedWidget.addWidget(self.page_serial)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        # setCentralWidget已在开头设置，这里删除重复调用

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)

        self.pushButton_2.clicked.connect(MainWindow.confirm_close)  # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "user"))
        self.pushButton_relogin.setText(_translate("MainWindow", ""))
        # self.pushButton_relogin.setStyleSheet("QPushButton {\
        # image: url(:/image/exit.png);\
        # background-color: transparent;\
        # color:  #2c3e50;\
        # border: none;\
        # padding: 8px 12px;\
        # }QPushButton:hover {\
        # color: #42b983;  /* Vue风格的悬停颜色 */\
        # }\
        # QPushButton:pressed {\
        #     color: #2d8d62;  /* 按下时更深的颜色 */\
        #     padding-left: 13px;  /* 向右移动1像素 */\
        #     padding-top: 9px;    /* 向下移动1像素 */\
        # }")
        #
        # self.pushButton_3.setStyleSheet("QPushButton {\
        # image: url(:/image/minimize.png);\
        # background-color: transparent;\
        # color:  #2c3e50;\
        # border: none;\
        # padding: 8px 12px;\
        # }QPushButton:hover {\
        # color: #42b983;  /* Vue风格的悬停颜色 */\
        # }\
        # QPushButton:pressed {\
        #     color: #2d8d62;  /* 按下时更深的颜色 */\
        #     padding-left: 13px;  /* 向右移动1像素 */\
        #     padding-top: 9px;    /* 向下移动1像素 */\
        # }")
        # self.pushButton_3.setStyleSheet("QPushButton {\
        #  image: url(:/image/close.png);\
        #  background-color: transparent;\
        #  color:  #2c3e50;\
        #  border: none;\
        #  padding: 8px 12px;\
        #  }QPushButton:hover {\
        #  color: #42b983;  /* Vue风格的悬停颜色 */\
        #  }\
        #  QPushButton:pressed {\
        #      color: #2d8d62;  /* 按下时更深的颜色 */\
        #      padding-left: 13px;  /* 向右移动1像素 */\
        #      padding-top: 9px;    /* 向下移动1像素 */\
        #  }")

        self.pushButton_exercise.setText(_translate("MainWindow", "练习试次"))
        self.pushButton_main.setText(_translate("MainWindow", "正式实验"))
        self.pushButton_highestscore.setText(_translate("MainWindow", "最好成绩"))
        self.pushButton_data.setText(_translate("MainWindow", "数据查看"))
        # self.pushButton_setting.setText(_translate("MainWindow", "端口设置"))
        self.label_welcome_subtitle.setText(_translate("MainWindow", "请仔细阅读以下实验说明"))
        # <<< MODIFICATION >>>
        # --- Updated instruction text ---
        # self.label_intro_content.setText(_translate("MainWindow",
        #                                             "<html><head/><body><p><span style=\" font-weight:600;\">本实验是一个合作绘图任务。</span>首次使用:请点击【练习任务】，完成练习后进入【正式实验】，熟悉操作后可直接点击【正式实验】</p><p>如下图所示，您的目标是尽可能准确、快速地复现目标图形。</p><p>• <span style=\" font-weight:600;\">练习试次</span>：熟悉系统操作，掌握绘图技巧。</p><p>• <span style=\" font-weight:600;\">正式实验</span>：完成正式的绘图任务测试。</p></body></html>"))
        self.label_intro_content.setText(_translate("MainWindow",
                                                                                                "<html><head/><body><p><span style=\" font-weight:600;\">本实验是一个协作绘图任务。</span>首次使用时,请点击【练习任务】，完成练习后进入【正式实验】，熟悉操作后可直接点击【正式实验】</p><p>如下图流程所示，您的目标是尽可能准确、快速地复现目标图形。</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "点击进入对应训练模块"))
        self.pushButton_4.setText(_translate("MainWindow", "人员①绘图练习模块"))
        self.pushButton_9.setText(_translate("MainWindow", "人员①&人员②绘图练习模块"))
        self.pushButton_10.setText(_translate("MainWindow", "人员①&人员③绘图练习模块"))
        self.label_3.setText(_translate("MainWindow", "点击按钮进行正式实验"))
        self.title_label.setText(_translate("MainWindow", "单人准确度排行榜"))
        self.first_rank_label.setStyleSheet("QLabel { image: url(:/image/1.png); }")
        self.first_user_label.setText(_translate("MainWindow", "用户"))
        self.first_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.first_time_label.setText(_translate("MainWindow", "用时: -"))
        self.first_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.first_date_label.setText(_translate("MainWindow", "日期: -"))
        # self.second_rank_label.setText(_translate("MainWindow", "🥈"))
        self.second_rank_label.setStyleSheet("QLabel { image: url(:/image/2.png); }")
        self.second_user_label.setText(_translate("MainWindow", "用户"))
        self.second_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.second_time_label.setText(_translate("MainWindow", "用时: -"))
        self.second_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.second_date_label.setText(_translate("MainWindow", "日期: -"))
        # self.third_rank_label.setText(_translate("MainWindow", "🥉"))
        self.third_rank_label.setStyleSheet("QLabel { image: url(:/image/3.png); }")
        self.third_user_label.setText(_translate("MainWindow", "用户"))
        self.third_accuracy_label.setText(_translate("MainWindow", "准确度: -"))
        self.third_time_label.setText(_translate("MainWindow", "用时: -"))
        self.third_deviation_label.setText(_translate("MainWindow", "偏差: -"))
        self.third_date_label.setText(_translate("MainWindow", "日期: -"))
        self.info_label.setText(_translate("MainWindow", "💡 排名基于准确度高低，偏差面积越小越好，用时越短越好"))
        self.label_4.setText(_translate("MainWindow", "点击按钮查看行为数据"))
        self.label_input_method_reminder.setText(_translate("MainWindow", "⚠️提醒：请确保切换到英文输入法"))
        self.pushButton_macro_guidance.setText(_translate("MainWindow", "实验介绍"))
        self.label_status_text.setText(_translate("MainWindow", "未连接"))


from src.utils import resouce_rc