# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import subprocess
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets

from src.utils import shared_data


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.resize(1872, 1290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(290, 90, 1481, 831))
        self.frame.setMinimumSize(QtCore.QSize(1481, 831))
        self.frame.setStyleSheet("#frame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:none;\n"
"font: 20pt \"微软雅黑\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/地球.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2.addWidget(self.frame_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_relogin = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_relogin.setFont(font)
        self.pushButton_relogin.setStyleSheet("QPushButton{\n"
"    border: 1px solid rgb(34, 92, 102);\n"
"    border-radius: 8px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 5px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_relogin.setIcon(icon1)
        self.pushButton_relogin.setIconSize(QtCore.QSize(80, 40))
        self.pushButton_relogin.setObjectName("pushButton_relogin")
        self.horizontalLayout_2.addWidget(self.pushButton_relogin)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:10px\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minimize (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"\n"
"    background-color: rgb(34, 92, 102);\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 50pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    color: rgb(17, 48, 53);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_exercise = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_exercise.setFont(font)
        self.pushButton_exercise.setIconSize(QtCore.QSize(5, 16))
        self.pushButton_exercise.setObjectName("pushButton_exercise")
        self.horizontalLayout_8.addWidget(self.pushButton_exercise)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_main = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_main.setObjectName("pushButton_main")
        self.horizontalLayout_9.addWidget(self.pushButton_main)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_highestscore = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_highestscore.setObjectName("pushButton_highestscore")
        self.horizontalLayout_10.addWidget(self.pushButton_highestscore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_data = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_data.setObjectName("pushButton_data")
        self.horizontalLayout_12.addWidget(self.pushButton_data)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_setting = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.horizontalLayout_11.addWidget(self.pushButton_setting)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 50pt \"微软雅黑\";\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget.addWidget(self.page_home)
        self.page_exercise = QtWidgets.QWidget()
        self.page_exercise.setObjectName("page_exercise")
        self.label_2 = QtWidgets.QLabel(self.page_exercise)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 751, 71))
        self.label_2.setStyleSheet("font-size: 50px")
        self.label_2.setObjectName("label_2")
        self.frame_11 = QtWidgets.QFrame(self.page_exercise)
        self.frame_11.setGeometry(QtCore.QRect(220, 180, 701, 550))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 20, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 10px 24px;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 110, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 10px 24px;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 200, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 10px 24px;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 290, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 10px 24px;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 380, 581, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(34, 92, 102);\n"
"    font: 28pt \"微软雅黑\";\n"
"    padding: 10px 24px;\n"
"    margin: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(34, 92, 102);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(17, 48, 53);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.stackedWidget.addWidget(self.page_exercise)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.run_main_test = QtWidgets.QPushButton(self.page_main)
        self.run_main_test.setGeometry(QtCore.QRect(520, 350, 101, 101))
        self.run_main_test.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    padding-bottom:20px\n"
"\n"
"}")
        self.run_main_test.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_main_test.setIcon(icon4)
        self.run_main_test.setIconSize(QtCore.QSize(160, 160))
        self.run_main_test.setObjectName("run_main_test")
        self.label_3 = QtWidgets.QLabel(self.page_main)
        self.label_3.setGeometry(QtCore.QRect(300, 220, 511, 71))
        self.label_3.setStyleSheet("font-size: 50px")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_main)
        self.page_highestscore = QtWidgets.QWidget()
        self.page_highestscore.setObjectName("page_highestscore")

        # 创建主标题
        self.title_label = QtWidgets.QLabel(self.page_highestscore)
        self.title_label.setGeometry(QtCore.QRect(300, 30, 500, 60))
        self.title_label.setText("🏆 准确度排行榜 TOP 3")
        self.title_label.setStyleSheet("""
            QLabel {
                font: bold 28pt "幼圆";
                color: rgb(34, 92, 102);
                text-align: center;
            }
        """)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)

        # 第一名框架
        self.first_place_frame = QtWidgets.QFrame(self.page_highestscore)
        self.first_place_frame.setGeometry(QtCore.QRect(100, 120, 280, 160))
        self.first_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #FFD700, stop:1 #FFA500);
                border: 3px solid #DAA520;
                border-radius: 12px;
            }
        """)

        # 第一名内容
        self.first_rank_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_rank_label.setGeometry(QtCore.QRect(10, 5, 40, 30))
        self.first_rank_label.setText("🥇")
        self.first_rank_label.setStyleSheet("font: 24pt; border: none;")

        self.first_user_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_user_label.setGeometry(QtCore.QRect(55, 5, 220, 30))
        self.first_user_label.setText("玩家名称")
        self.first_user_label.setStyleSheet("font: bold 16pt '幼圆'; color: #8B4513; border: none;")

        self.first_accuracy_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_accuracy_label.setGeometry(QtCore.QRect(10, 40, 260, 30))
        self.first_accuracy_label.setText("准确度: 98.5%")
        self.first_accuracy_label.setStyleSheet("font: bold 14pt '幼圆'; color: #8B4513; border: none;")

        self.first_deviation_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_deviation_label.setGeometry(QtCore.QRect(10, 75, 260, 25))
        self.first_deviation_label.setText("偏差面积: 0.25")
        self.first_deviation_label.setStyleSheet("font: 12pt '幼圆'; color: #8B4513; border: none;")

        self.first_time_label = QtWidgets.QLabel(self.first_place_frame)
        self.first_time_label.setGeometry(QtCore.QRect(10, 105, 260, 25))
        self.first_time_label.setText("用时: 2分30秒")
        self.first_time_label.setStyleSheet("font: 12pt '幼圆'; color: #8B4513; border: none;")

        # 第二名框架
        self.second_place_frame = QtWidgets.QFrame(self.page_highestscore)
        self.second_place_frame.setGeometry(QtCore.QRect(420, 140, 260, 140))
        self.second_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #C0C0C0, stop:1 #A9A9A9);
                border: 3px solid #808080;
                border-radius: 12px;
            }
        """)

        # 第二名内容
        self.second_rank_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_rank_label.setGeometry(QtCore.QRect(10, 5, 40, 30))
        self.second_rank_label.setText("🥈")
        self.second_rank_label.setStyleSheet("font: 22pt; border: none;")

        self.second_user_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_user_label.setGeometry(QtCore.QRect(55, 5, 200, 30))
        self.second_user_label.setText("玩家名称")
        self.second_user_label.setStyleSheet("font: bold 14pt '幼圆'; color: #2F4F4F; border: none;")

        self.second_accuracy_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_accuracy_label.setGeometry(QtCore.QRect(10, 40, 240, 25))
        self.second_accuracy_label.setText("准确度: 96.8%")
        self.second_accuracy_label.setStyleSheet("font: bold 12pt '幼圆'; color: #2F4F4F; border: none;")

        self.second_deviation_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_deviation_label.setGeometry(QtCore.QRect(10, 70, 240, 20))
        self.second_deviation_label.setText("偏差面积: 0.42")
        self.second_deviation_label.setStyleSheet("font: 11pt '幼圆'; color: #2F4F4F; border: none;")

        self.second_time_label = QtWidgets.QLabel(self.second_place_frame)
        self.second_time_label.setGeometry(QtCore.QRect(10, 95, 240, 20))
        self.second_time_label.setText("用时: 3分15秒")
        self.second_time_label.setStyleSheet("font: 11pt '幼圆'; color: #2F4F4F; border: none;")

        # 第三名框架
        self.third_place_frame = QtWidgets.QFrame(self.page_highestscore)
        self.third_place_frame.setGeometry(QtCore.QRect(720, 160, 240, 120))
        self.third_place_frame.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #CD7F32, stop:1 #B8860B);
                border: 3px solid #8B4513;
                border-radius: 12px;
            }
        """)

        # 第三名内容
        self.third_rank_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_rank_label.setGeometry(QtCore.QRect(10, 5, 35, 25))
        self.third_rank_label.setText("🥉")
        self.third_rank_label.setStyleSheet("font: 20pt; border: none;")

        self.third_user_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_user_label.setGeometry(QtCore.QRect(50, 5, 180, 25))
        self.third_user_label.setText("玩家名称")
        self.third_user_label.setStyleSheet("font: bold 12pt '幼圆'; color: #FFFAF0; border: none;")

        self.third_accuracy_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_accuracy_label.setGeometry(QtCore.QRect(10, 35, 220, 20))
        self.third_accuracy_label.setText("准确度: 94.2%")
        self.third_accuracy_label.setStyleSheet("font: bold 11pt '幼圆'; color: #FFFAF0; border: none;")

        self.third_deviation_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_deviation_label.setGeometry(QtCore.QRect(10, 60, 220, 18))
        self.third_deviation_label.setText("偏差面积: 0.68")
        self.third_deviation_label.setStyleSheet("font: 10pt '幼圆'; color: #FFFAF0; border: none;")

        self.third_time_label = QtWidgets.QLabel(self.third_place_frame)
        self.third_time_label.setGeometry(QtCore.QRect(10, 83, 220, 18))
        self.third_time_label.setText("用时: 4分02秒")
        self.third_time_label.setStyleSheet("font: 10pt '幼圆'; color: #FFFAF0; border: none;")

        # 底部说明文字
        self.info_label = QtWidgets.QLabel(self.page_highestscore)
        self.info_label.setGeometry(QtCore.QRect(200, 320, 600, 40))
        self.info_label.setText("💡 排名基于准确度高低，偏差面积越小越好，用时越短越好")
        self.info_label.setStyleSheet("""
            QLabel {
                font: 14pt "幼圆";
                color: rgb(100, 100, 100);
                text-align: center;
            }
        """)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)

        self.stackedWidget.addWidget(self.page_highestscore)
        self.page_data = QtWidgets.QWidget()
        self.page_data.setObjectName("page_data")
        self.data_check = QtWidgets.QPushButton(self.page_data)
        self.data_check.setGeometry(QtCore.QRect(520, 350, 141, 131))
        self.data_check.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    padding-bottom:20px\n"
"\n"
"}")
        self.data_check.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_check.setIcon(icon5)
        self.data_check.setIconSize(QtCore.QSize(150, 150))
        self.data_check.setObjectName("data_check")
        self.label_4 = QtWidgets.QLabel(self.page_data)
        self.label_4.setGeometry(QtCore.QRect(300, 220, 511, 71))
        self.label_4.setStyleSheet("font-size: 50px")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_data)
        self.page_serial = QtWidgets.QWidget()
        self.page_serial.setObjectName("page_serial")
        # 英文输入法提醒标签
        self.label_input_method_reminder = QtWidgets.QLabel(self.page_serial)
        self.label_input_method_reminder.setGeometry(QtCore.QRect(200, 10, 800, 60))
        self.label_input_method_reminder.setStyleSheet("QLabel{\n"
"    border: 2px solid rgb(255, 165, 0);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 248, 220);\n"
"    color: rgb(255, 140, 0);\n"
"    font: bold 25pt \"微软雅黑\";\n"
"    padding: 10px;\n"
"}")
        self.label_input_method_reminder.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_method_reminder.setObjectName("label_input_method_reminder")
        self.frame_8 = QtWidgets.QFrame(self.page_serial)
        self.frame_8.setGeometry(QtCore.QRect(130, 120, 801, 551))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 342, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_com = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_com.setObjectName("label_com")
        self.verticalLayout_5.addWidget(self.label_com)
        self.label_bote = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_bote.setObjectName("label_bote")
        self.verticalLayout_5.addWidget(self.label_bote)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(359, -1, 441, 231))
        self.frame_9.setStyleSheet(" QComboBox {\n"
"                font-size: 60px;  /* 设置字体大小 */\n"
"\n"
"                text-align: center; /* 居中对齐 */\n"
"            }")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.comboBox_bote = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_bote.setGeometry(QtCore.QRect(30, 130, 391, 81))
        self.comboBox_bote.setIconSize(QtCore.QSize(40, 40))
        self.comboBox_bote.setObjectName("comboBox_bote")
        self.comboBox_bote.addItem("")
        self.comboBox_bote.addItem("")
        self.comboBox_bote.addItem("")
        self.comboBox_bote.addItem("")
        self.comboBox_bote.addItem("")
        self.comboBox_com = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_com.setGeometry(QtCore.QRect(30, 10, 391, 81))
        self.comboBox_com.setIconSize(QtCore.QSize(40, 40))
        self.comboBox_com.setObjectName("comboBox_com")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.comboBox_com.addItem("")
        self.label_connection_status = QtWidgets.QLabel(self.frame_8)
        self.label_connection_status.setGeometry(QtCore.QRect(330, 270, 200, 200))
        self.label_connection_status.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    border-radius: 100px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.label_connection_status.setText("")
        self.label_connection_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_connection_status.setObjectName("label_connection_status")
        self.label_status_text = QtWidgets.QLabel(self.frame_8)
        self.label_status_text.setGeometry(QtCore.QRect(330, 480, 200, 50))
        self.label_status_text.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color: rgb(255, 0, 0);\n"
"    font: 30pt \"微软雅黑\";\n"
"}")
        self.label_status_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_text.setObjectName("label_status_text")
        self.pushButton_quereng = QtWidgets.QPushButton(self.page_serial)
        self.pushButton_quereng.setGeometry(QtCore.QRect(930, 640, 161, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_quereng.setFont(font)
        self.pushButton_quereng.setStyleSheet("QPushButton{\n"
"background-color: rgb(34, 92, 102);\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 50pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    color: rgb(17, 48, 53);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_quereng.setObjectName("pushButton_quereng")
        self.pushButton_test_send = QtWidgets.QPushButton(self.page_serial)
        self.pushButton_test_send.setGeometry(QtCore.QRect(1110, 640, 140, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_test_send.setFont(font)
        self.pushButton_test_send.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 150, 0);\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 40pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 120, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_test_send.setObjectName("pushButton_test_send")
        self.stackedWidget.addWidget(self.page_serial)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.comboBox_bote.setCurrentIndex(3)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        user1 = getattr(shared_data, 'user1_mark', None)
        user2 = getattr(shared_data, 'user2_mark', None)
        user3 = getattr(shared_data, 'user3_mark', None)

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "user"))
        self.pushButton_relogin.setText(_translate("MainWindow", "重新登录"))
        self.pushButton_exercise.setText(_translate("MainWindow", "练习试次"))
        self.pushButton_main.setText(_translate("MainWindow", "正式实验"))
        self.pushButton_highestscore.setText(_translate("MainWindow", "最好成绩"))
        self.pushButton_data.setText(_translate("MainWindow", "数据查看"))
        self.pushButton_setting.setText(_translate("MainWindow", "端口设置"))
        self.label_2.setText(_translate("MainWindow", "点击进入对应训练模块"))
        # 设置默认按钮文本，避免显示None
        if user1:
            self.pushButton_4.setText(_translate("MainWindow", f"{user1}绘图练习模块"))
        else:
            self.pushButton_4.setText(_translate("MainWindow", "人员①绘图练习模块"))
            
        if user2:
            self.pushButton_5.setText(_translate("MainWindow", f"{user2}绘图练习模块"))
        else:
            self.pushButton_5.setText(_translate("MainWindow", "人员②绘图练习模块"))
            
        if user3:
            self.pushButton_6.setText(_translate("MainWindow", f"{user3}绘图练习模块"))
        else:
            self.pushButton_6.setText(_translate("MainWindow", "人员③绘图练习模块"))
            
        if user1 and user2:
            self.pushButton_9.setText(_translate("MainWindow", f"{user1}&{user2}绘图练习模块"))
        else:
            self.pushButton_9.setText(_translate("MainWindow", "人员①&人员②绘图练习模块"))
            
        if user1 and user3:
            self.pushButton_10.setText(_translate("MainWindow", f"{user1}&{user3}绘图练习模块"))
        else:
            self.pushButton_10.setText(_translate("MainWindow", "人员①&人员③绘图练习模块"))
        self.label_3.setText(_translate("MainWindow", "点击按钮进行正式实验"))
        self.label_4.setText(_translate("MainWindow", "点击按钮查看行为数据"))
        self.label_com.setText(_translate("MainWindow", "端口号："))
        self.label_bote.setText(_translate("MainWindow", "波特率："))
        self.comboBox_bote.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox_bote.setItemText(1, _translate("MainWindow", "19200"))
        self.comboBox_bote.setItemText(2, _translate("MainWindow", "38400"))
        self.comboBox_bote.setItemText(3, _translate("MainWindow", "57600"))
        self.comboBox_bote.setItemText(4, _translate("MainWindow", "115200"))
        self.comboBox_com.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboBox_com.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboBox_com.setItemText(2, _translate("MainWindow", "COM3"))
        self.comboBox_com.setItemText(3, _translate("MainWindow", "COM4"))
        self.comboBox_com.setItemText(4, _translate("MainWindow", "COM5"))
        self.comboBox_com.setItemText(5, _translate("MainWindow", "COM6"))
        self.label_status_text.setText(_translate("MainWindow", "未连接"))
        self.label_input_method_reminder.setText(_translate("MainWindow", "⚠️提醒：请确保切换到英文输入法"))
        self.pushButton_quereng.setText(_translate("MainWindow", "确定"))
        self.pushButton_test_send.setText(_translate("MainWindow", "测试发送指令"))
from src.utils import resouce_rc



