# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 900))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(102, 126, 234, 255), stop:1 rgba(118, 75, 162, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_container = QtWidgets.QWidget(self.centralwidget)
        self.main_container.setGeometry(QtCore.QRect(100, 100, 1200, 700))
        self.main_container.setStyleSheet("QWidget#main_container {\n"
"    background: white;\n"
"    border-radius: 25px;\n"
"}")
        self.main_container.setObjectName("main_container")
        self.left_panel = QtWidgets.QLabel(self.main_container)
        self.left_panel.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.left_panel.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(68, 72, 95, 255), stop:1 rgba(15, 9, 32, 255));\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"    border-image: url(:/images/images/21.jpg);\n"
"}")
        self.left_panel.setText("")
        self.left_panel.setObjectName("left_panel")
        self.left_overlay = QtWidgets.QWidget(self.left_panel)
        self.left_overlay.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.left_overlay.setStyleSheet("QWidget {\n"
"    background: rgba(0, 0, 0, 120);\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"}")
        self.left_overlay.setObjectName("left_overlay")
        self.right_panel = QtWidgets.QWidget(self.main_container)
        self.right_panel.setGeometry(QtCore.QRect(600, 0, 600, 700))
        self.right_panel.setStyleSheet("QWidget#right_panel {\n"
"    background: white;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}")
        self.right_panel.setObjectName("right_panel")
        self.login_title = QtWidgets.QLabel(self.right_panel)
        self.login_title.setGeometry(QtCore.QRect(110, 100, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.login_title.setFont(font)
        self.login_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.login_title.setAlignment(QtCore.Qt.AlignCenter)
        self.login_title.setObjectName("login_title")
        self.task_selection_card = QtWidgets.QWidget(self.right_panel)
        self.task_selection_card.setGeometry(QtCore.QRect(50, 180, 481, 160))
        self.task_selection_card.setStyleSheet("QWidget#task_selection_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#task_selection_card:hover {\n"
"    border: 2px solid #667eea;\n"
"    background: #f0fff4;\n"
"}")
        self.task_selection_card.setObjectName("task_selection_card")
        self.task_selection_title = QtWidgets.QLabel(self.task_selection_card)
        self.task_selection_title.setGeometry(QtCore.QRect(20, 20, 350, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.task_selection_title.setFont(font)
        self.task_selection_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.task_selection_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.task_selection_title.setObjectName("task_selection_title")
        self.task_button_container = QtWidgets.QWidget(self.task_selection_card)
        self.task_button_container.setGeometry(QtCore.QRect(20, 65, 441, 85))
        self.task_button_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.task_button_container.setObjectName("task_button_container")
        self.subject_a_card = QtWidgets.QWidget(self.right_panel)
        self.subject_a_card.setGeometry(QtCore.QRect(50, 360, 481, 160))
        self.subject_a_card.setStyleSheet("QWidget#subject_a_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#subject_a_card:hover {\n"
"    border: 2px solid #667eea;\n"
"    background: #f8f9ff;\n"
"}")
        self.subject_a_card.setObjectName("subject_a_card")
        self.subject_a_icon = QtWidgets.QLabel(self.subject_a_card)
        self.subject_a_icon.setGeometry(QtCore.QRect(-100, 20, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.subject_a_icon.setFont(font)
        self.subject_a_icon.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(102, 126, 234, 255), stop:1 rgba(118, 75, 162, 255));\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}")
        self.subject_a_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_a_icon.setObjectName("subject_a_icon")
        self.subject_a_title = QtWidgets.QLabel(self.subject_a_card)
        self.subject_a_title.setGeometry(QtCore.QRect(20, 20, 350, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subject_a_title.setFont(font)
        self.subject_a_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.subject_a_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subject_a_title.setObjectName("subject_a_title")
        self.subject_a_ellipse_container = QtWidgets.QWidget(self.subject_a_card)
        self.subject_a_ellipse_container.setGeometry(QtCore.QRect(20, 65, 441, 85))
        self.subject_a_ellipse_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.subject_a_ellipse_container.setObjectName("subject_a_ellipse_container")
        self.final_login_button = QtWidgets.QPushButton(self.right_panel)
        self.final_login_button.setGeometry(QtCore.QRect(150, 580, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.final_login_button.setFont(font)
        self.final_login_button.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(46, 204, 113, 255), stop:1 rgba(39, 174, 96, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(39, 174, 96, 255), stop:1 rgba(34, 153, 84, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(34, 153, 84, 255), stop:1 rgba(30, 130, 76, 255));\n"
"}")
        self.final_login_button.setObjectName("final_login_button")
        self.frame_5 = QtWidgets.QFrame(self.right_panel)
        self.frame_5.setGeometry(QtCore.QRect(490, 0, 112, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:10px\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimize_button = QtWidgets.QPushButton(self.frame_5)
        self.minimize_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minimize (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon)
        self.minimize_button.setIconSize(QtCore.QSize(40, 40))
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout_3.addWidget(self.minimize_button)
        self.close_button = QtWidgets.QPushButton(self.frame_5)
        self.close_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon1)
        self.close_button.setIconSize(QtCore.QSize(40, 40))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_3.addWidget(self.close_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "实验系统登录"))
        self.login_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">合作行为能力评估软件</span></p></body></html>"))
        self.task_selection_title.setText(_translate("MainWindow", "任务代号"))
        self.subject_a_icon.setText(_translate("MainWindow", "航天员"))
        self.subject_a_title.setText(_translate("MainWindow", "被测航天员"))
        self.final_login_button.setText(_translate("MainWindow", "登录"))
from src.utils import resouce_rc
