# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 900))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(102, 126, 234, 255), stop:1 rgba(118, 75, 162, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_container = QtWidgets.QWidget(self.centralwidget)
        self.main_container.setGeometry(QtCore.QRect(100, 100, 1200, 700))
        self.main_container.setStyleSheet("QWidget#main_container {\n"
"    background: white;\n"
"    border-radius: 25px;\n"
"}")
        self.main_container.setObjectName("main_container")
        self.left_panel = QtWidgets.QLabel(self.main_container)
        self.left_panel.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.left_panel.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(68, 72, 95, 255), stop:1 rgba(15, 9, 32, 255));\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"    border-image: url(:/images/images/21.jpg);\n"
"}")
        self.left_panel.setText("")
        self.left_panel.setObjectName("left_panel")
        self.left_overlay = QtWidgets.QWidget(self.left_panel)
        self.left_overlay.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.left_overlay.setStyleSheet("QWidget {\n"
"    background: rgba(0, 0, 0, 120);\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"}")
        self.left_overlay.setObjectName("left_overlay")
        self.right_panel = QtWidgets.QWidget(self.main_container)
        self.right_panel.setGeometry(QtCore.QRect(600, 0, 600, 700))
        self.right_panel.setStyleSheet("QWidget#right_panel {\n"
"    background: white;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}")
        self.right_panel.setObjectName("right_panel")
        self.close_button = QtWidgets.QPushButton(self.right_panel)
        self.close_button.setGeometry(QtCore.QRect(540, 15, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("QPushButton {\n"
"    background: #ff5f56;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #ff3b30;\n"
"}")
        self.close_button.setObjectName("close_button")
        self.minimize_button = QtWidgets.QPushButton(self.right_panel)
        self.minimize_button.setGeometry(QtCore.QRect(500, 15, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.minimize_button.setFont(font)
        self.minimize_button.setStyleSheet("QPushButton {\n"
"    background: #ffbd2e;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #ff9500;\n"
"}")
        self.minimize_button.setObjectName("minimize_button")
        self.login_title = QtWidgets.QLabel(self.right_panel)
        self.login_title.setGeometry(QtCore.QRect(50, 20, 500, 40))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_title.setFont(font)
        self.login_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.login_title.setAlignment(QtCore.Qt.AlignCenter)
        self.login_title.setObjectName("login_title")
        self.task_selection_card = QtWidgets.QWidget(self.right_panel)
        self.task_selection_card.setGeometry(QtCore.QRect(50, 120, 500, 140))
        self.task_selection_card.setStyleSheet("QWidget#task_selection_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#task_selection_card:hover {\n"
"    border: 2px solid #2ecc71;\n"
"    background: #f0fff4;\n"
"}")
        self.task_selection_card.setObjectName("task_selection_card")
        self.task_selection_title = QtWidgets.QLabel(self.task_selection_card)
        self.task_selection_title.setGeometry(QtCore.QRect(20, 15, 140, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.task_selection_title.setFont(font)
        self.task_selection_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.task_selection_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.task_selection_title.setObjectName("task_selection_title")
        self.task_button_container = QtWidgets.QWidget(self.task_selection_card)
        self.task_button_container.setGeometry(QtCore.QRect(30, 50, 440, 65))
        self.task_button_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.task_button_container.setObjectName("task_button_container")
        self.subject_a_card = QtWidgets.QWidget(self.right_panel)
        self.subject_a_card.setGeometry(QtCore.QRect(50, 300, 500, 160))
        self.subject_a_card.setStyleSheet("QWidget#subject_a_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#subject_a_card:hover {\n"
"    border: 2px solid #667eea;\n"
"    background: #f8f9ff;\n"
"}")
        self.subject_a_card.setObjectName("subject_a_card")
        self.subject_a_icon = QtWidgets.QLabel(self.subject_a_card)
        self.subject_a_icon.setGeometry(QtCore.QRect(-100, 20, 80, 40))  # 隐藏图标
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.subject_a_icon.setFont(font)
        self.subject_a_icon.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(102, 126, 234, 255), stop:1 rgba(118, 75, 162, 255));\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}")
        self.subject_a_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_a_icon.setObjectName("subject_a_icon")
        self.subject_a_title = QtWidgets.QLabel(self.subject_a_card)
        self.subject_a_title.setGeometry(QtCore.QRect(20, 20, 350, 40))  # 与任务编号对齐
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subject_a_title.setFont(font)
        self.subject_a_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.subject_a_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subject_a_title.setObjectName("subject_a_title")
        self.subject_a_ellipse_container = QtWidgets.QWidget(self.subject_a_card)
        self.subject_a_ellipse_container.setGeometry(QtCore.QRect(20, 65, 460, 85))  # 与文字对齐
        self.subject_a_ellipse_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.subject_a_ellipse_container.setObjectName("subject_a_ellipse_container")
        self.subject_b_card = QtWidgets.QWidget(self.right_panel)
        self.subject_b_card.setGeometry(QtCore.QRect(50, 320, 500, 140))
        self.subject_b_card.setStyleSheet("QWidget#subject_b_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#subject_b_card:hover {\n"
"    border: 2px solid #f093fb;\n"
"    background: #fef7ff;\n"
"}")
        self.subject_b_card.setObjectName("subject_b_card")
        self.subject_b_icon = QtWidgets.QLabel(self.subject_b_card)
        self.subject_b_icon.setGeometry(QtCore.QRect(30, 20, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.subject_b_icon.setFont(font)
        self.subject_b_icon.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(240, 147, 251, 255), stop:1 rgba(245, 87, 108, 255));\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}")
        self.subject_b_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_b_icon.setObjectName("subject_b_icon")
        self.subject_b_title = QtWidgets.QLabel(self.subject_b_card)
        self.subject_b_title.setGeometry(QtCore.QRect(125, 20, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subject_b_title.setFont(font)
        self.subject_b_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.subject_b_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subject_b_title.setObjectName("subject_b_title")
        self.subject_b_ellipse_container = QtWidgets.QWidget(self.subject_b_card)
        self.subject_b_ellipse_container.setGeometry(QtCore.QRect(30, 65, 440, 65))
        self.subject_b_ellipse_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.subject_b_ellipse_container.setObjectName("subject_b_ellipse_container")
        self.subject_c_card = QtWidgets.QWidget(self.right_panel)
        self.subject_c_card.setGeometry(QtCore.QRect(50, 480, 500, 140))
        self.subject_c_card.setStyleSheet("QWidget#subject_c_card {\n"
"    background: white;\n"
"    border: 2px solid #e1e5e9;\n"
"    border-radius: 16px;\n"
"}\n"
"QWidget#subject_c_card:hover {\n"
"    border: 2px solid #e67e22;\n"
"    background: #fef9f3;\n"
"}")
        self.subject_c_card.setObjectName("subject_c_card")
        self.subject_c_icon = QtWidgets.QLabel(self.subject_c_card)
        self.subject_c_icon.setGeometry(QtCore.QRect(30, 20, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.subject_c_icon.setFont(font)
        self.subject_c_icon.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(230, 126, 34, 255), stop:1 rgba(211, 84, 0, 255));\n"
"    border-radius: 20px;\n"
"    color: white;\n"
"}")
        self.subject_c_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_c_icon.setObjectName("subject_c_icon")
        self.subject_c_title = QtWidgets.QLabel(self.subject_c_card)
        self.subject_c_title.setGeometry(QtCore.QRect(125, 20, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.subject_c_title.setFont(font)
        self.subject_c_title.setStyleSheet("QLabel {\n"
"    color: #333;\n"
"    background: transparent;\n"
"}")
        self.subject_c_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subject_c_title.setObjectName("subject_c_title")
        self.subject_c_ellipse_container = QtWidgets.QWidget(self.subject_c_card)
        self.subject_c_ellipse_container.setGeometry(QtCore.QRect(30, 65, 440, 65))
        self.subject_c_ellipse_container.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"}")
        self.subject_c_ellipse_container.setObjectName("subject_c_ellipse_container")
        self.final_login_button = QtWidgets.QPushButton(self.right_panel)
        self.final_login_button.setGeometry(QtCore.QRect(150, 550, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.final_login_button.setFont(font)
        self.final_login_button.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(46, 204, 113, 255), stop:1 rgba(39, 174, 96, 255));\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 30px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(39, 174, 96, 255), stop:1 rgba(34, 153, 84, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(34, 153, 84, 255), stop:1 rgba(30, 130, 76, 255));\n"
"}")
        self.final_login_button.setObjectName("final_login_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close_button.clicked.connect(MainWindow.close) # type: ignore
        self.minimize_button.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "实验系统登录"))
        self.close_button.setText(_translate("MainWindow", "×"))
        self.minimize_button.setText(_translate("MainWindow", "−"))
        self.login_title.setText(_translate("MainWindow", "人员身份登录"))
        self.task_selection_title.setText(_translate("MainWindow", "任务代号:"))
        self.subject_a_icon.setText(_translate("MainWindow", "航天员"))
        self.subject_a_title.setText(_translate("MainWindow", "佩戴脑电帽的航天员"))
        self.subject_b_icon.setText(_translate("MainWindow", "副航天员"))
        self.subject_b_title.setText(_translate("MainWindow", "人员②"))
        self.subject_c_icon.setText(_translate("MainWindow", "副航天员"))
        self.subject_c_title.setText(_translate("MainWindow", "人员③"))
        self.final_login_button.setText(_translate("MainWindow", "登录"))
from src.utils import resouce_rc
